<map version="1.0.1">
<!-- To view this file, download free mind mapping software FreeMind from http://freemind.sourceforge.net -->
<node CREATED="1400677591296" ID="ID_1838286313" MODIFIED="1400677612961" TEXT="Social Network Analysis Project">
<node CREATED="1400677614660" ID="ID_1910278327" MODIFIED="1400677616176" POSITION="right" TEXT="Notes">
<node CREATED="1400680550432" ID="ID_1145363036" MODIFIED="1400680555420" TEXT="Comment from Gwilym">
<node CREATED="1400680557369" MODIFIED="1400680557369">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <span style="letter-spacing: normal; font-size: x-small; text-transform: none; white-space: normal; display: inline !important; text-align: start; font-weight: normal; font-variant: normal; background-color: rgb(255, 255, 255); text-indent: 0px; line-height: normal; word-spacing: 0px; float: none; font-family: Tahoma; font-style: normal; color: rgb(0, 0, 0)"><font color="rgb(0, 0, 0)" size="x-small" face="Tahoma">thanks Jon. One thought came to mind following our meeting on Monday. If we think it's a bit dubious running the ERG model on separate parts of the city, how about we run it on multiple random sub-samples of 100 observations? A sort of bootstrapping approach... Best, g.</font></span>
  </body>
</html>
</richcontent>
</node>
</node>
</node>
<node CREATED="1400677616611" ID="ID_275502712" MODIFIED="1400677618608" POSITION="right" TEXT="Background"/>
<node CREATED="1400677618859" ID="ID_446286066" MODIFIED="1400677622664" POSITION="right" TEXT="Deadlines">
<node CREATED="1400678045024" MODIFIED="1400678045024">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <p class="MsoNormal" style="margin-bottom: 0px; letter-spacing: normal; margin-right: 0px; font-size: 13px; text-transform: none; white-space: normal; text-align: start; font-weight: normal; font-variant: normal; background-color: rgb(255, 255, 255); text-indent: 0px; line-height: normal; word-spacing: 0px; margin-top: 0px; font-family: arial, sans-serif; margin-left: 0px; font-style: normal; color: rgb(34, 34, 34)">
      <span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)"><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">Yes, a tight deadline indeed, though Vonu is very keen to have us involved so we might be able to squeeze a bit more time if needed. Just to confirm: if I can&#8217;t make the conference due to moving house, are you still able to go in my place to present? Dates are 11-12 August. My travel will get paid from UBDC I think but your travel could be funded by AQMEN or the School. Maybe you could submit an application to the School conference budget? I copy below the abstract we submitted.</font></span>
    </p>
    <p class="MsoNormal" style="margin-bottom: 0px; letter-spacing: normal; margin-right: 0px; font-size: 13px; text-transform: none; white-space: normal; text-align: start; font-weight: normal; font-variant: normal; background-color: rgb(255, 255, 255); text-indent: 0px; line-height: normal; word-spacing: 0px; margin-top: 0px; font-family: arial, sans-serif; margin-left: 0px; font-style: normal; color: rgb(34, 34, 34)">
      <span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)"><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">&#160;</font></span>
    </p>
    <p class="MsoNormal" style="margin-bottom: 0px; letter-spacing: normal; margin-right: 0px; font-size: 13px; text-transform: none; white-space: normal; text-align: start; font-weight: normal; font-variant: normal; background-color: rgb(255, 255, 255); text-indent: 0px; line-height: normal; word-spacing: 0px; margin-top: 0px; font-family: arial, sans-serif; margin-left: 0px; font-style: normal; color: rgb(34, 34, 34)">
      <span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)"><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">So, we have until 15<sup>th</sup></font></span><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif"><span class="Apple-converted-space">&#160;</span><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)">July to write a conference paper. Here&#8217;s the plan:</span></font>
    </p>
    <p class="MsoNormal" style="margin-bottom: 0px; letter-spacing: normal; margin-right: 0px; font-size: 13px; text-transform: none; white-space: normal; text-align: start; font-weight: normal; font-variant: normal; background-color: rgb(255, 255, 255); text-indent: 0px; line-height: normal; word-spacing: 0px; margin-top: 0px; font-family: arial, sans-serif; margin-left: 0px; font-style: normal; color: rgb(34, 34, 34)">
      <span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)"><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">&#160;</font></span>
    </p>
    <p style="letter-spacing: normal; font-size: 13px; text-transform: none; white-space: normal; text-align: start; font-weight: normal; font-variant: normal; background-color: rgb(255, 255, 255); text-indent: 0px; line-height: normal; word-spacing: 0px; font-family: arial, sans-serif; font-style: normal; color: rgb(34, 34, 34)">
      <b><span><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">1.</font></span><span style="font-size: 7pt; font-weight: normal; font-variant: normal; line-height: normal; font-family: Times New Roman; font-style: normal"><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman">&#160;&#160;&#160;&#160;&#160;</font></span><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman"><span class="Apple-converted-space">&#160;</span></font><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)"><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">wb 12<sup>th</sup></font></span><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif"><span class="Apple-converted-space">&#160;</span><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)">May:</span></font></b>
    </p>
    <p style="letter-spacing: normal; font-size: 13px; text-transform: none; white-space: normal; text-align: start; font-weight: normal; font-variant: normal; background-color: rgb(255, 255, 255); text-indent: 0px; line-height: normal; word-spacing: 0px; font-family: arial, sans-serif; font-style: normal; margin-left: 72pt; color: rgb(34, 34, 34)">
      <span><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">a.</font></span><span style="font-size: 7pt; font-weight: normal; font-variant: normal; line-height: normal; font-family: Times New Roman; font-style: normal"><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman">&#160;&#160;&#160;&#160;&#160;</font></span><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman"><span class="Apple-converted-space">&#160;</span></font><b><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)"><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">Gwilym</font></span></b><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif"><span class="Apple-converted-space">&#160;</span><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)">to work on the language data using the same textual categorisation as Oates &amp; Pryce. This will initially be done at dwelling level. We will need to decide whether to aggregate this up to output area or datazone. I will do both, but I propose we initially work with datazones.</span></font>
    </p>
    <p style="letter-spacing: normal; font-size: 13px; text-transform: none; white-space: normal; text-align: start; font-weight: normal; font-variant: normal; background-color: rgb(255, 255, 255); text-indent: 0px; line-height: normal; word-spacing: 0px; font-family: arial, sans-serif; font-style: normal; margin-left: 72pt; color: rgb(34, 34, 34)">
      <span><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">b.</font></span><span style="font-size: 7pt; font-weight: normal; font-variant: normal; line-height: normal; font-family: Times New Roman; font-style: normal"><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman">&#160;&#160;&#160;&#160;&#160;</font></span><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman"><span class="Apple-converted-space">&#160;</span></font><b><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)"><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">Jon</font></span></b><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif"><span class="Apple-converted-space">&#160;</span><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)">to email Nema to ask what R package she used to do the social network analysis (or perhaps you can work this out from Nema&#8217;s slides?).</span></font>
    </p>
    <p style="letter-spacing: normal; font-size: 13px; text-transform: none; white-space: normal; text-align: start; font-weight: normal; font-variant: normal; background-color: rgb(255, 255, 255); text-indent: 0px; line-height: normal; word-spacing: 0px; font-family: arial, sans-serif; font-style: normal; color: rgb(34, 34, 34)">
      <span><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">2.</font></span><span style="font-size: 7pt; font-weight: normal; font-variant: normal; line-height: normal; font-family: Times New Roman; font-style: normal"><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman">&#160;&#160;&#160;&#160;&#160;</font></span><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman"><span class="Apple-converted-space">&#160;</span></font><b><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)"><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">wb 19<sup>th</sup></font></span><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif"><span class="Apple-converted-space">&#160;</span><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)">May:</span></font></b>
    </p>
    <p style="letter-spacing: normal; font-size: 13px; text-transform: none; white-space: normal; text-align: start; font-weight: normal; font-variant: normal; background-color: rgb(255, 255, 255); text-indent: 0px; line-height: normal; word-spacing: 0px; font-family: arial, sans-serif; font-style: normal; margin-left: 72pt; color: rgb(34, 34, 34)">
      <span><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">a.</font></span><span style="font-size: 7pt; font-weight: normal; font-variant: normal; line-height: normal; font-family: Times New Roman; font-style: normal"><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman">&#160;&#160;&#160;&#160;&#160;</font></span><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman"><span class="Apple-converted-space">&#160;</span></font><b><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)"><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">Jon</font></span><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif"><span class="Apple-converted-space">&#160;</span></font></b><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif"><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)">to take Gwilym&#8217;s data and create a social network for 2011. Do some initial measures of network structure. Then test whether distance between nodes (i.e. datazone centroids) affects the probability of their being a link between nodes.</span></font>
    </p>
    <p style="letter-spacing: normal; font-size: 13px; text-transform: none; white-space: normal; text-align: start; font-weight: normal; font-variant: normal; background-color: rgb(255, 255, 255); text-indent: 0px; line-height: normal; word-spacing: 0px; font-family: arial, sans-serif; font-style: normal; margin-left: 72pt; color: rgb(34, 34, 34)">
      <span><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">b.</font></span><span style="font-size: 7pt; font-weight: normal; font-variant: normal; line-height: normal; font-family: Times New Roman; font-style: normal"><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman">&#160;&#160;&#160;&#160;&#160;</font></span><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman"><span class="Apple-converted-space">&#160;</span></font><b><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)"><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">Jon</font></span></b><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif"><span class="Apple-converted-space">&#160;</span><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)">to add in node variables from SNS on ethnicity and demography</span></font>
    </p>
    <p style="letter-spacing: normal; font-size: 13px; text-transform: none; white-space: normal; text-align: start; font-weight: normal; font-variant: normal; background-color: rgb(255, 255, 255); text-indent: 0px; line-height: normal; word-spacing: 0px; font-family: arial, sans-serif; font-style: normal; margin-left: 72pt; color: rgb(34, 34, 34)">
      <span><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">c.</font></span><span style="font-size: 7pt; font-weight: normal; font-variant: normal; line-height: normal; font-family: Times New Roman; font-style: normal"><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman">&#160;&#160;&#160;&#160;&#160;</font></span><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman"><span class="Apple-converted-space">&#160;</span></font><b><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)"><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">Gwilym</font></span></b><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif"><span class="Apple-converted-space">&#160;</span><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)">draft paper structure and initial literature review.</span></font>
    </p>
    <p style="letter-spacing: normal; font-size: 13px; text-transform: none; white-space: normal; text-align: start; font-weight: normal; font-variant: normal; background-color: rgb(255, 255, 255); text-indent: 0px; line-height: normal; word-spacing: 0px; font-family: arial, sans-serif; font-style: normal; color: rgb(34, 34, 34)">
      <b><span><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">3.</font></span><span style="font-size: 7pt; font-weight: normal; font-variant: normal; line-height: normal; font-family: Times New Roman; font-style: normal"><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman">&#160;&#160;&#160;&#160;&#160;</font></span><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman"><span class="Apple-converted-space">&#160;</span></font><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)"><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">Wb 26<sup>th</sup></font></span><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif"><span class="Apple-converted-space">&#160;</span><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)">May:</span></font></b>
    </p>
    <p style="letter-spacing: normal; font-size: 13px; text-transform: none; white-space: normal; text-align: start; font-weight: normal; font-variant: normal; background-color: rgb(255, 255, 255); text-indent: 0px; line-height: normal; word-spacing: 0px; font-family: arial, sans-serif; font-style: normal; margin-left: 72pt; color: rgb(34, 34, 34)">
      <span><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">a.</font></span><span style="font-size: 7pt; font-weight: normal; font-variant: normal; line-height: normal; font-family: Times New Roman; font-style: normal"><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman">&#160;&#160;&#160;&#160;&#160;</font></span><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman"><span class="Apple-converted-space">&#160;</span></font><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)"><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">Jon to test for homophily in ethnicity in 2011 and repeat the analysis for 2001.</font></span>
    </p>
    <p style="letter-spacing: normal; font-size: 13px; text-transform: none; white-space: normal; text-align: start; font-weight: normal; font-variant: normal; background-color: rgb(255, 255, 255); text-indent: 0px; line-height: normal; word-spacing: 0px; font-family: arial, sans-serif; font-style: normal; margin-left: 72pt; color: rgb(34, 34, 34)">
      <span><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">b.</font></span><span style="font-size: 7pt; font-weight: normal; font-variant: normal; line-height: normal; font-family: Times New Roman; font-style: normal"><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman">&#160;&#160;&#160;&#160;&#160;</font></span><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman"><span class="Apple-converted-space">&#160;</span></font><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)"><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">Jon to re-run the analysis using % change between 2001 and 2011. i.e. the network now becomes a dynamic one, where we use % change in language as the basis for links between datazones, and the covariates are in % change also (% change in ethnicity). Compute homophily measures.</font></span>
    </p>
    <p style="letter-spacing: normal; font-size: 13px; text-transform: none; white-space: normal; text-align: start; font-weight: normal; font-variant: normal; background-color: rgb(255, 255, 255); text-indent: 0px; line-height: normal; word-spacing: 0px; font-family: arial, sans-serif; font-style: normal; color: rgb(34, 34, 34)">
      <span><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">4.</font></span><span style="font-size: 7pt; font-weight: normal; font-variant: normal; line-height: normal; font-family: Times New Roman; font-style: normal"><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman">&#160;&#160;&#160;&#160;&#160;</font></span><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman"><span class="Apple-converted-space">&#160;</span></font><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)"><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">wb 2<sup>nd</sup></font></span><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif"><span class="Apple-converted-space">&#160;</span><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)">June:</span></font>
    </p>
    <p style="letter-spacing: normal; font-size: 13px; text-transform: none; white-space: normal; text-align: start; font-weight: normal; font-variant: normal; background-color: rgb(255, 255, 255); text-indent: 0px; line-height: normal; word-spacing: 0px; font-family: arial, sans-serif; font-style: normal; margin-left: 72pt; color: rgb(34, 34, 34)">
      <span><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">a.</font></span><span style="font-size: 7pt; font-weight: normal; font-variant: normal; line-height: normal; font-family: Times New Roman; font-style: normal"><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman">&#160;&#160;&#160;&#160;&#160;</font></span><font color="rgb(31, 73, 125)" size="7pt" face="Times New Roman"><span class="Apple-converted-space">&#160;</span></font><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)"><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">Gwilym to write up the results and the rest of the paper.</font></span>
    </p>
    <p class="MsoNormal" style="margin-bottom: 0px; letter-spacing: normal; margin-right: 0px; font-size: 13px; text-transform: none; white-space: normal; text-align: start; font-weight: normal; font-variant: normal; background-color: rgb(255, 255, 255); text-indent: 0px; line-height: normal; word-spacing: 0px; margin-top: 0px; font-family: arial, sans-serif; margin-left: 0px; font-style: normal; color: rgb(34, 34, 34)">
      <span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)"><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">&#160;</font></span>
    </p>
    <p class="MsoNormal" style="margin-bottom: 0px; letter-spacing: normal; margin-right: 0px; font-size: 13px; text-transform: none; white-space: normal; text-align: start; font-weight: normal; font-variant: normal; background-color: rgb(255, 255, 255); text-indent: 0px; line-height: normal; word-spacing: 0px; margin-top: 0px; font-family: arial, sans-serif; margin-left: 0px; font-style: normal; color: rgb(34, 34, 34)">
      <span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(31, 73, 125)"><font color="rgb(31, 73, 125)" size="11pt" face="Calibri, sans-serif">This will give us the rest of June to revise and update the paper. What do you think? The attached may be of some use in terms of providing an example of similar analysis based on house price movements.</font></span>
    </p>
  </body>
</html>
</richcontent>
</node>
</node>
<node CREATED="1400677622883" ID="ID_1880801428" MODIFIED="1400677624391" POSITION="right" TEXT="Commitments"/>
<node CREATED="1400677624659" ID="ID_1081782902" MODIFIED="1400677627143" POSITION="right" TEXT="Deliverables"/>
<node CREATED="1400677681855" ID="ID_449802906" MODIFIED="1400677692971" POSITION="right" TEXT="Acronyms">
<node CREATED="1400677694694" ID="ID_821928417" MODIFIED="1400677697979" TEXT="BDUIC">
<node CREATED="1400677700358" ID="ID_751746164" MODIFIED="1400677708586" TEXT="Big Data and Urban Informatics"/>
</node>
</node>
<node CREATED="1400677716829" ID="ID_393509437" MODIFIED="1400677725481" POSITION="right" TEXT="Workshops">
<node CREATED="1400677726172" ID="ID_849883611" MODIFIED="1400677732465" TEXT="BUUIC">
<node CREATED="1400677737292" ID="ID_1127061114" MODIFIED="1400677745560" TEXT="August 11-12, 2014"/>
<node CREATED="1400677748907" ID="ID_972735443" MODIFIED="1400677753583" TEXT="Title">
<node CREATED="1400677754651" ID="ID_105282077" MODIFIED="1400677787301" TEXT="&quot;The effect of ethnic mix on the marketing language of residential property: A social network analysis&quot;"/>
</node>
<node CREATED="1400678014986" ID="ID_1242680017" MODIFIED="1400678016766" TEXT="Abstract">
<node CREATED="1400677835237" ID="ID_1560768302" MODIFIED="1400677835237">
<richcontent TYPE="NODE"><html>
  <head>
    
  </head>
  <body>
    <span style="font-size: 14pt; font-family: Garamond, serif"><font color="rgb(34, 34, 34)" size="14pt" face="Garamond, serif"><b style="letter-spacing: normal; font-size: 13px; text-transform: none; white-space: normal; text-align: start; font-variant: normal; background-color: rgb(255, 255, 255); text-indent: 0px; line-height: normal; word-spacing: 0px; font-family: arial, sans-serif; font-style: normal; color: rgb(34, 34, 34)">Abstract:</b></font></span><font color="rgb(34, 34, 34)" size="14pt" face="Garamond, serif"><span class="Apple-converted-space">&#160;</span><span style="letter-spacing: normal; font-size: 14pt; text-transform: none; text-align: start; white-space: normal; font-weight: normal; font-variant: normal; background-color: rgb(255, 255, 255); text-indent: 0px; word-spacing: 0px; line-height: normal; font-family: Garamond, serif; font-style: normal; color: rgb(34, 34, 34)">This paper conceptualises real estate marketing language formation as a social network. We use this theoretical framework, and the fact that estate agents seek to reflect buyer aspirations, to interpret patterns of language as indicators of social perceptions of an area. Data on a large number of house transactions are then used to explore the relationship between the ethnic mix of an area and the language used, using a breakdown of seller hyperbole based on Aristotle&#8217;s theory of rhetoric. Because of the interdependence of estate agent language variation proposed by the social network framework, we then relax the assumption of independence between transactions and apply social network analysis to language variation over time exploring the degree of homophily&#8212;the extent to which similar dwellings in similar neighbourhoods have similar patterns of marketing language. We use the model to investigate the particular question of whether changes in the ethnic and religious mix of a neighbourhood lead to measureable changes in the co-movement of language variation between areas.</span></font>
  </body>
</html></richcontent>
</node>
</node>
</node>
</node>
<node CREATED="1400677831350" ID="ID_756974536" LINK="../../../../C:/Users/jm383x/Downloads/Housing%20markets%20as%20social%20networks_v1u.pdf" MODIFIED="1400678027053" POSITION="right" TEXT="Current Manuscript"/>
<node CREATED="1400678078174" ID="ID_1513783407" MODIFIED="1400678082138" POSITION="left" TEXT="Actions">
<node CREATED="1400680484419" ID="ID_1923671736" MODIFIED="1400680485968" TEXT="To do"/>
<node CREATED="1400680486483" ID="ID_551597307" MODIFIED="1400680487857" TEXT="Completed">
<node CREATED="1400678084221" ID="ID_1540255798" MODIFIED="1400678089705" TEXT="Email Nema to ask for more data"/>
</node>
</node>
</node>
</map>
